name: rpc
version: 0.6.2
description: Library for exposing Dart server-side APIs.
homepage: https://github.com/dart-lang/rpc

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  args: ^2.3.0
  collection: ^1.15.0
  convert: ^3.0.1
  crypto: ^3.0.1
  discoveryapis_generator: ^1.0.0
  gcloud: ^0.8.3
  http_parser: ^4.0.0
  logging: ^1.0.2
  mime: ^1.0.0
  path: ^1.8.0
  uri: ^1.0.0

dev_dependencies:
  test: ^1.17.12

